spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.177.98:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
  redis:
    port: 6379
    host: 127.0.0.1
    password: root
    timeout: 5000
    jedis:
      pool:
        max-idle: 10
        max-wait: 3
        max-active: 10
server:
  port: 8080
#无需 xml 的sql 就不需要配置
#mybatis:
#    type-aliases-package: cn.plateform.mappers
#    mapper-locations: classpath:mappers/*.xml